// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGHJUCW7l9uTFCECJEyVKpvPu7Que3QGQ',
    appId: '1:643890129689:web:19e34d1349522ec97bb388',
    messagingSenderId: '643890129689',
    projectId: 'todo-list-app-cc03a',
    authDomain: 'todo-list-app-cc03a.firebaseapp.com',
    storageBucket: 'todo-list-app-cc03a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Oaxx218yyfMMcs0JqscRmontFlUN2ic',
    appId: '1:643890129689:android:d438c1fac2e14ffa7bb388',
    messagingSenderId: '643890129689',
    projectId: 'todo-list-app-cc03a',
    storageBucket: 'todo-list-app-cc03a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSi2XloiNjN1J9ee6KBUhl4n-E7z62ziA',
    appId: '1:643890129689:ios:27b8b7c2816cde9d7bb388',
    messagingSenderId: '643890129689',
    projectId: 'todo-list-app-cc03a',
    storageBucket: 'todo-list-app-cc03a.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSi2XloiNjN1J9ee6KBUhl4n-E7z62ziA',
    appId: '1:643890129689:ios:27b8b7c2816cde9d7bb388',
    messagingSenderId: '643890129689',
    projectId: 'todo-list-app-cc03a',
    storageBucket: 'todo-list-app-cc03a.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );
}
